---
title: "LimnoPalettes"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Table of Contents

* [Citing package](#cite)
* [Installation](#install)
* [Examples](#examp)

Code and general idea inspired by the ["Wes Anderson Palettes"](https://github.com/karthik/wesanderson) R-Package.

## Citing package <a name="cite"></a>

```{r}
citation('LimnoPalettes')
```

## Installation <a name="install"></a>

```{r,eval=F}
install.packages("devtools");# if you do not have it installed on your PC
devtools::install_github("SwampThingPaul/LimnoPalettes")
```


## Now Presenting... <a name="examp"></a>

```{r iowa,fig.height=5,fig.width=7,align='center',echo=FALSE,message=FALSE,warning=FALSE}
library(imager)
library(LimnoPalettes)

im=load.image("./images/SummerIowaLakes_GWilkinson.jpg")

par(family="serif",mar=c(0,0,0,0))
layout(matrix(1:3,3,1),heights=c(1,1,0.25))
plot(im,ann=F,axes=F)
print.palette(limno_palette("IowaSummer"),txt.cex=2)
plot(0:1,0:1,ann=F,axes=F,type="n")
text(0,0.5,"Photo Credit: Grace Wilkinson (Twitter: goodgracious23)",adj=0)
```

```{r PeriFA,fig.height=5,fig.width=7,align='center',echo=FALSE,message=FALSE,warning=FALSE}
im=load.image("./images/PeriphytonFA_MMeyer.jpg")

par(family="serif",mar=c(0,0,0,0))
layout(matrix(1:3,3,1),heights=c(1,1,0.25))
plot(im,ann=F,axes=F)
print.palette(limno_palette("PeriFA"),txt.cex=2)
plot(0:1,0:1,ann=F,axes=F,type="n")
text(0,0.5,"Photo Credit: Michael Meyer (Twitter: mishafredmeyer)",adj=0)
```

```{r Bloom1,fig.height=5,fig.width=7,align='center',echo=FALSE,message=FALSE,warning=FALSE}
im=load.image("./images/Bloom1_SBurnet.jpg")

par(family="serif",mar=c(0,0,0,0))
layout(matrix(1:3,3,1),heights=c(1,1,0.25))
plot(im,ann=F,axes=F)
print.palette(limno_palette("Bloom1"),txt.cex=2)
plot(0:1,0:1,ann=F,axes=F,type="n")
text(0,0.5,"Photo Credit: Sarah Burnet (Twitter: limnosarah)",adj=0)
```

```{r Bloom2,fig.height=5,fig.width=7,align='center',echo=FALSE,message=FALSE,warning=FALSE}
im=load.image("./images/Bloom2_SBurnet.jpg")

par(family="serif",mar=c(0,0,0,0))
layout(matrix(1:3,3,1),heights=c(1,1,0.25))
plot(im,ann=F,axes=F)
print.palette(limno_palette("Bloom2"),txt.cex=2)
plot(0:1,0:1,ann=F,axes=F,type="n")
text(0,0.5,"Photo Credit: Sarah Burnet (Twitter: limnosarah)",adj=0)
```

```{r SuperIce,fig.height=5,fig.width=7,align='center',echo=FALSE,message=FALSE,warning=FALSE}
im=load.image("./images/LakeSuperiorIce_SBurnet.jpg")

par(family="serif",mar=c(0,0,0,0))
layout(matrix(1:3,3,1),heights=c(1,1,0.25))
plot(im,ann=F,axes=F)
print.palette(limno_palette("SuperIce"),txt.cex=2)
plot(0:1,0:1,ann=F,axes=F,type="n")
text(0,0.5,"Photo Credit: Sarah Burnet (Twitter: limnosarah)",adj=0)
```

```{r FlatheadRocks,fig.height=5,fig.width=7,align='center',echo=FALSE,message=FALSE,warning=FALSE}
im=load.image("./images/FlatheadLake_PJulian.jpg")

par(family="serif",mar=c(0,0,0,0))
layout(matrix(1:3,3,1),heights=c(1,1,0.25))
plot(im,ann=F,axes=F)
print.palette(limno_palette("FlatheadRocks"),txt.cex=2)
plot(0:1,0:1,ann=F,axes=F,type="n")
text(0,0.5,"Photo Credit: Paul Julian (Twitter: SwampThingPaul)",adj=0)
```

```{r ShelburnePond,fig.height=5,fig.width=7,align='center',echo=FALSE,message=FALSE,warning=FALSE}
im=load.image("./images/ShelburnePond_LBorre.jpg")

par(family="serif",mar=c(0,0,0,0))
layout(matrix(1:3,3,1),heights=c(1,1,0.25))
plot(im,ann=F,axes=F)
print.palette(limno_palette("ShelburnePond"),txt.cex=2)
plot(0:1,0:1,ann=F,axes=F,type="n")
text(0,0.5,"Photo Credit: Lisa Borre (Twitter: lisa_borre)",adj=0)
```

```{r WetSoil,fig.height=5,fig.width=7,align='center',echo=FALSE,message=FALSE,warning=FALSE}
im=load.image("./images/wetsoil_RKBhomia.jpg")

par(family="serif",mar=c(0,0,0,0))
layout(matrix(1:3,3,1),heights=c(1,1,0.25))
plot(im,ann=F,axes=F)
print.palette(limno_palette("WetSoil"),txt.cex=2)
plot(0:1,0:1,ann=F,axes=F,type="n")
text(0,0.5,"Photo Credit: Rupesh K Bhomia (Twitter: RupeshKBhomia)",adj=0)
```

```{r OrdRiver,fig.height=5,fig.width=7,align='center',echo=FALSE,message=FALSE,warning=FALSE}
im=load.image("./images/OrdRiverWA_CFowler.jpg")

par(family="serif",mar=c(0,0,0,0))
layout(matrix(1:3,3,1),heights=c(1,1,0.25))
plot(im,ann=F,axes=F)
print.palette(limno_palette("OrdRiver"),txt.cex=2)
plot(0:1,0:1,ann=F,axes=F,type="n")
text(0,0.5,"Photo Credit: Courtney Fowler (Twitter: courtzfowler)",adj=0)
```

***
